apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: msb3xav8c-java-springboot
  janus-idp.io/tekton: msb3xav8c-java-springboot
  backstage.io/kubernetes-id: msb3xav8c-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: msb3xav8c-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
